// Generated by https://quicktype.io

export interface CreateOrderResponse {
  id:             string;
  status:         string;
  payment_source: PaymentSource;
  links:          Link[];
}

export interface Link {
  href:   string;
  rel:    string;
  method: string;
}

export interface PaymentSource {
  paypal: Paypal;
}

export interface Paypal {
}
