// Generated by https://quicktype.io

import { Client } from "./client.model";
import { Service } from "./service.model";

export interface Order {
  id: string;
  client: Client;
  service: Service;
  address: string;
  location: string;
  city: string;
  zipCode: string;
  startDate: string;
  endDate: string;
  price: number;
  hours: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}
